# Generated by Django 5.2 on 2025-04-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='create_date',
            field=models.DateField(auto_now=True),
        ),
    ]
