# Generated by Django 5.2 on 2025-04-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='create_date',
            new_name='createDate',
        ),
    ]
